### ISSUE TITLE
Tracker Offline: cannot generate SL leader report

### ISSUE THREAD

**Issue by sikler** [CMSTrackerDPG/certifier#100]
Tried to generate "Shift leader report" through certhelper.

Error messages are attached
[KeyError at _shiftleader_.pdf](https://github.com/CMSTrackerDPG/certifier/files/8213278/KeyError.at._shiftleader_.pdf)

Could you help?

Thanks,
 Ferenc (tracker offline SL)

**Comment by nothingface0** [comment]
Thank you @sikler for the report

@Abhit03 
The failing datasets from the RunRegistry ([348396, 348401, 348403, 348409]) have "Commissioning22" as their class attribute.
When the code reaches [this point](https://github.com/CMSTrackerDPG/certifier/blob/abece8ef730de1b1d3fc6252b7db84f8f946d7d0/shiftleader/utilities/utilities.py#L59), the `if-elifs` are not satisfied (they only account for "collisions" and "cosmics"), so no `runreconstruction__run__run_type` is assigned. 

What "run type" should be assigned to them?
 

To test in openshift:
```python
import runregistry
from shiftleader.utilities.utilities import convert_run_registry_to_trackercertification
run_numbers = [348396, 348401, 348403, 348409]
keys =  ['runreconstruction__run__run_number',  'runreconstruction__run__run_type',  'runreconstruction__reconstruction',  'pixel',  'strip',  'tracking']
run_registry_entries = runregistry.get_datasets(filter={'run_number': {'or': run_numbers}, 'dataset_name': {'notlike':'%online%'}})
convert_run_registry_to_trackercertification(run_registry_entries)
run_registry_entries[0].keys()
```

**Comment by sikler** [comment]
Hi, these are cosmics.

**Comment by nothingface0** [comment]
So is it safe to categorize all "Commissioning" datasets as "cosmics"?

**Comment by sikler** [comment]
I don't know. Some flag must have been erroneously set to collisions, I guess.

**Comment by sroychow** [comment]
> So is it safe to categorize all "Commissioning" datasets as "cosmics"?

I don't think so.  You can have a Commissioning run during collisions. These are probably Commissioning since Strips are missing, so it is not the Cosmics setup. @arossi83 please correct me if I am wrong.

**Comment by nothingface0** [comment]
Ok, we are working to get more info for the run before assuming its type.

E.g. we can get `hlt_key` from `oms_attributes` which looks something like `"/cdaq/cosmic/commissioning2022/CRAFT/v1.1/GPU/HLT/V4"`

**Comment by sikler** [comment]
@nothingface0 Thanks, works well now!

**Comment by nothingface0** [comment]
No worries!

PS: Hooray for the 100th issue!
