### ISSUE TITLE
[ShiftLeader] Add extra information to Run Registry Report

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/certifier#108]
From @arossi83:

> in the ShiftLeader view there is a quite useful tab to perform a comparison between FLAG in CertHelperDB and Runregistry. It will be great to add a column to the run registry report with the status of that run (OPEN, SIGNEDOFF, COMPLETED), this will be very useful

**Comment by arossi83** [comment]
Here also a different background color on the RunRegistry columns will work (i.e. Red==OPEN Orange==SignedOff Grey as now==completed)

**Comment by nothingface0** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/8612771/165339113-9937eae9-4030-4a7b-822c-7990fa9bd646.png)
