### ISSUE TITLE
Booking of runs from open runs app not working as intended

### ISSUE THREAD

**Issue by sroychow** [CMSTrackerDPG/certifier#110]
It has been reported by the shift crew that runs booked by one shifter are visible to other shifters via the ```Certify a new run``` app. They can also edit that run. See e.g. snapshot below.
![image](https://user-images.githubusercontent.com/6286474/160375114-cad81db1-319e-4205-983a-57fd08bf44f6.png)

Here, the runs booked by Roberval can be edited by other shifters.

**Comment by connorpa** [comment]
wished behaviour (repeating what was said on the MM channel):
 - no automatic assignment
 - add a button somewhere to book a shift

**Comment by nothingface0** [comment]
Verified using the following procedure:
- Created test local account with `Shifter` rights.
- Navigate to `Certify a Run`
- Run `349433` which is currently booked shows as greyed out (as intended), `Express` is yellow but cannot be clicked (as intended)
- On the top input field, pasting `349433` and clicking on `Certify` redirects to the `/certify` page, effectively bypassing the booking.
