### ISSUE TITLE
Re thinking assignment of runs in Cert Helper

### ISSUE THREAD

**Issue by sroychow** [CMSTrackerDPG/certifier#111]
At the moment, when an user searches for open runs via ```Certification```, the runs are automatically assigned to the user. This feature is not desirable. The correct feature for this should be:-

1. Get open runs should return all the ```open``` runs listed in the query range by the user. 
2. Beside each run, there should be button called ```certify/assign myself```, only then that run should be assigned to that user.
3. Once the ```certify/assign``` button is clicked by an user,  that run should not be editable by other users.

@arossi83 thoughts on this?

**Comment by nothingface0** [comment]
From a UI's point of view, this sounds a lot more rational and expected. The fact that searching for something does something else than just listing results can only lead to confusion.

**Comment by connorpa** [comment]
any progress?

**Comment by nothingface0** [comment]
Including a part of the conversatoin from Mattermost:

> Currently, as the app is structured, once the user "books" a run, _only they_ can certify independent reconstructions belonging to this run. This was (from what we understand) the concept of the "Open Run". A user "books" it, and only they can certify any reconstruction for this run. 
> 
> This was reflected by how the whole run turns grey when the user "books" it. As @connorpa noticed, logging in as a different user, by using the top form in the Certify a new run window one can bypass this block, allowing you to override the existing certification (for a specific combination of run + reconstruction type). That's the functionality that was fixed in #110. 
> 
> In retrospect, it seems like this is not the intended behavior. It seems like each reconstruction for a run should (?) be independent, and should be "certifiable" by different shifters. This means that the behavior described in issue #111 might not the behavior we are looking for.
