### ISSUE TITLE
[ReferenceRuns] Add extra information to reference runs list

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/certifier#124]
Add extra information as shown in [this Twiki page](https://twiki.cern.ch/twiki/bin/view/CMS/TrackerOfflineReferenceRuns)

- era (from `OmsFill`)
- APV mode (from ???)
- B-field (from `OmsFill`)
- pile-up (from `OmsFill`)
- colliding bunches (from `OmsFill`)

**Comment by nothingface0** [comment]
@sroychow, @arossi83: Where can one find the `APV mode` information? I can't find it on RunRegistry or OMS. Am I missing something?

**Comment by arossi83** [comment]
here where to get the APV mode:
http://ebutz.web.cern.ch/ebutz/cgi-bin/getReadOutmodeMulti.pl
?FIRSTRUN=str(minrun)&LASTRUN=str(maxrun)

this is the call to get a all the runs in a range. if you want a single run use this instead:
http://ebutz.web.cern.ch/ebutz/cgi-bin/getReadOutmode.pl?RUN=str(runnumber)

**Comment by nothingface0** [comment]
Thanks a lot @arossi83
