### ISSUE TITLE
Allow use of `/certify/` page even if RR/OMS are down

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/certifier#134]
In case of RR/OMS API downtime, Certhelper should not fail to run, but allow the users to manually enter the missing information.

- Add a new empty entry for OmsRun, TrackerCertification (TODO: check all model entries created during certification)
- Allow saving with most fields empty.
- ~~Add functionality/button to fetch data _after_ the initial manual entry has been created (e.g. `Fetch updated data`)~~ Will be added as a separate issue

-----

Certification Expected behavior:
- [x] If run reconstruction certification exists, update existing without crashing
- [x] If run reconstruction certification does not exist, warn the user and proceed to create a manual entry. 
- [ ] ~~Should there be a modal to add extra info?~~ Maybe in another issue

**Comment by sroychow** [comment]
I think if the first 2 bullets are addressed, then it is fine. In any case, we don't need all the fields eventually for the DC process. In any case, e.g., if OMS is down, even the shifter won't be able to access the information from the webpage. So the following fields should be the min entries that a user has to fill:-

- Run number
- Type of certification - express/prompt
- Fill number(if accessible)
- Flags to be set as usual.
@arossi83 when you have time, please have a look at the suggestion.

**Comment by nothingface0** [comment]
@sroychow That's very useful info, thanks! :)
