### ISSUE TITLE
Add addtional tools to cert helper

### ISSUE THREAD

**Issue by sroychow** [CMSTrackerDPG/certifier#152]
Some additional tools need to be integrated with the cert helper. The first in the single module occupancy plotter. A script to perform the job exists in CMSSW and it can be executed from command line. In the figure attached, I propose an overview of how the form should look like on CertHelper. The main logic to launch the script should be similar to driving the TkMaps from CertHelper
![additionaltool](https://user-images.githubusercontent.com/6286474/169484234-8cbb3572-4f7c-4a2d-bf68-a128de1c5940.jpg)
.

**Comment by sroychow** [comment]
@sroychow will take care of preparing the script on vocms066

**Comment by nothingface0** [comment]
@sroychow I checked the sketch you posted above and I would like to ask more information on the following:

# Inputs
- `Datataking_period`: What kind of input is this? 
  - Should it be just a **string** which is typed by the user? What if the string is invalid?
  - Should it be a **dropdown** populated with valid choices? If so, where can one retrieve a list of valid choices?
- `StreamExpressCosmics/StreamExpress`:
  -  Is this a **toggle** between the two options?
- `Run number`:
  - Is this the usual `int` input?
- `Module list`:
  - What does this represent? 
  - What kind of input is this (same question as above: `string`, `int`, a dropdown?)

# Outputs
- Where are the images generated stored? What filename will they have? 
- What kind and of errors does the script throw?
- How many different failure scenarios can you predict?
  - e.g. What if the inputs are wrong?

**Comment by sroychow** [comment]
- ``` Datataking_period```: good question. Dropdown option seems to be the best choice. The data taking period is changed in once in ~2 months or so, and in that case the tool can be updated. Question - if the names of the data taking period are saved in a text file and pushed to the repo, will the tool be able to pick it up?
- ```StreamExpressCosmics/StreamExpress``` : yes
- ```Run number```: yes int
- ```Module list```: a list of integers. The det id of the modules for which the plots are requested.
