### ISSUE TITLE
Special PDs for TkMap generation during scan runs

### ISSUE THREAD

**Issue by tvami** [CMSTrackerDPG/certifier#217]
The tracker maps script (`tkmapsFromCertHelper.sh`) can only take ZB as input, but when we do scans everything will go to SpecialHLTPhysics1, one example is run 359579

**Comment by tvami** [comment]
@arossi83 @cardinia

**Comment by nothingface0** [comment]
No need for a PR, the options are customizable, so I understand that the option was added by @sroychow from the admin panel. Closing!

**Comment by sroychow** [comment]
@nothingface0 Both the CMSSW script and Certhelper needed updates. However, the driver script did not need any update. The script is already workng.
