### ISSUE TITLE
[Training Instance of CertHelper] Would it be possible to show the checklists like the production one?

### ISSUE THREAD

**Issue by gbenelli** [CMSTrackerDPG/certifier#98]
It seems the training instance does not show the various checklists (General, TrackerMaps, Pixel, Strips, Tracking), that are normally shown in the regular instance: could we add them to the training instance?

**Comment by nothingface0** [comment]
I've loaded the same checklist data from the certhelper instance. Please check that it's working as expected.

For developers' future reference:
```bash
# On certhelper pod
pip install pyyaml
python manage.py dumpdata checklists --format=yaml > checklists.yaml

# On training-certhelper pod
pip install pyyaml
python manage.py loaddata checklists.yaml
```

**Comment by gbenelli** [comment]
Thank you @nothingface0 !
