### ISSUE TITLE
Tracker Offline: how to generate tracker maps?

### ISSUE THREAD

**Issue by sikler** [CMSTrackerDPG/certifier#99]
I tried through https://certhelper.web.cern.ch/trackermaps/, but that does not work.

When I try to follow https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackerOfflineShiftInstructions -> Detailed instructions -> Produce and check Tracker Maps, I get

ssh cctrack@vocms061.cern.ch -XY
ssh: Could not resolve hostname vocms061.cern.ch: Name or service not known

Could you help?
Would need that for cosmic express runs 348396 - 348440.

Thanks,
 Ferenc (tracker offline SL)

**Comment by sroychow** [comment]
assign @sroychow 
I am working on it.

**Comment by sikler** [comment]
Hi @sroychow ,

We have now a nice run with strips in from last nighy: 348594, would be good to get a tracker map for that.
(In addition, there were two shorter, 348587 and 348590, if possible would be nice to include them too)

Thanks,
 Ferenc (tracker offline SL)

**Comment by sroychow** [comment]
@sikler  the maps are produced. Please check 

https://tkmaps.web.cern.ch/tkmaps/

Let me know if some run is missing.

**Comment by sikler** [comment]
Thanks very much!
